MODEL:
  BACKBONE:
    NAME: "build_timm_backbone"
  WEIGHTS: "models/resnet50_miil_21k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  TIMM:
    BASE_NAME: resnet50_in21k
DATASETS:
  TRAIN: ("lvvis_train",)
  TEST: ("lvvis_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (1000,)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 1000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (360, 480)
  MIN_SIZE_TEST: 360
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (600, 720)
  FORMAT: "RGB"
  SAMPLING_FRAME_NUM: 2
  SAMPLING_FRAME_RANGE: 20
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 50
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
